/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32f4xx.h"

#define THRESHOLD 2000  // Change based on your sensor range

void GPIO_Init(void) {
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;     // Enable GPIOA clock

    // PA5 as output for LED
    GPIOA->MODER &= ~(3 << (5 * 2));
    GPIOA->MODER |=  (1 << (5 * 2));

    // PA1 as analog input for moisture sensor
    GPIOA->MODER |= (3 << (1 * 2));          // Analog mode
}

void ADC1_Init(void) {
    RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;      // Enable ADC1 clock

    ADC1->CR2 = 0;                           // Reset control register
    ADC1->SQR3 = 1;                          // Channel 1 (PA1)
    ADC1->SMPR2 |= (7 << 3);                 // Sample time for channel 1
    ADC1->CR2 |= ADC_CR2_ADON;              // Enable ADC1
}

uint16_t ADC_Read(void) {
    ADC1->CR2 |= ADC_CR2_SWSTART;           // Start ADC conversion
    while (!(ADC1->SR & ADC_SR_EOC));       // Wait for conversion to complete
    return ADC1->DR;                         // Return ADC value
}

void delay(volatile uint32_t t) {
    while (t--);
}

int main(void) {
    GPIO_Init();
    ADC1_Init();

    while (1) {
        uint16_t moisture = ADC_Read();

        if (moisture > THRESHOLD) {
            GPIOA->ODR |= (1 << 5);  // Turn LED ON
        } else {
            GPIOA->ODR &= ~(1 << 5); // Turn LED OFF
        }

        delay(100000);
    }
}

